spring.application.name=bank
spring.datasource.url=jdbc:postgresql://localhost:5432/test_bank
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.data.jpa.repositories.enabled=false
